### ISSUE TITLE
Puppeteer > PhantomJS

### ISSUE THREAD

**Issue by stefanosaittamrf** [dominguezcelada/rent-flat-scraper#12]
### Description

I think we should migrate this project from the legacy PhantomJS to the hipster puppeteer.

### More infos

PhantomJS in 2018? Seriously it need  a further explanation of why?

**Comment by oscard0m** [comment]
Let's go with Puppeteer ! 🎖

**Comment by juanchaur** [comment]
https://giphy.com/gifs/xT8qBjoId2zA9cCyTS/html5

**Comment by nerder** [comment]
Close for now because it needs an architectural discussion before.
