### ISSUE TITLE
Add testing suite

### ISSUE THREAD

**Issue by nerder** [dominguezcelada/rent-flat-scraper#23]
## Description
To add a test suite to make our code and new changes reliable.

## Which test suite to use?
[![](https://api.gh-polls.com/poll/01CJ4991B7HTG8EH92PWZ7VQA6/Mocha%20%2B%20Chai%20%2B%20Sinon)](https://api.gh-polls.com/poll/01CJ4991B7HTG8EH92PWZ7VQA6/Mocha%20%2B%20Chai%20%2B%20Sinon/vote)
[![](https://api.gh-polls.com/poll/01CJ4991B7HTG8EH92PWZ7VQA6/JasmineJS)](https://api.gh-polls.com/poll/01CJ4991B7HTG8EH92PWZ7VQA6/JasmineJS/vote)

**Comment by oscard0m** [comment]
![image](https://user-images.githubusercontent.com/2574275/42479656-31ec673c-83da-11e8-95b6-1b7a5c6435be.png)
Discussion in progress to choose the technology

**Comment by stefanosaittamrf** [comment]
Let's go for `Mocha + Chai + Sinon`

**Comment by dominguezcelada** [comment]
### Which testing suite? 
/poll 'Mocha + Chai + Sinon' 'Jasmine'

**Comment by dominguezcelada** [comment]
# Which testing suite?
[![](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option1)](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Mocha%20+%20Chai%20+%20Sinon/vote)
[![](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/Option%202)](https://api.gh-polls.com/poll/01BY7ECS60GG8F9AR1VMR8745S/JasmineJS/vote)

**Comment by oscard0m** [comment]
Changed description to add a poll in Github! 👏 🎉
